=== 8Bitz0/volkanicmc-construct/schemas/format-3-overlay.json
{"$schema":"http://json-schema.org/draft-07/schema#","title":"Overlay","type":"object","required":["description","name","resources","saveables","template-format"],"properties":{"author":{"type":["string","null"]},"description":{"type":"string"},"name":{"type":"string"},"resources":{"type":"array","items":{"$ref":"#/definitions/GenericResource"}},"runtime":{"anyOf":[{"$ref":"#/definitions/ServerRuntimeResource"},{"type":"null"}]},"saveables":{"type":"array","items":{"type":"string"}},"template-format":{"type":"integer","format":"uint","minimum":0.0},"version":{"type":["array","null"],"items":[{"type":"integer","format":"uint64","minimum":0.0},{"type":["integer","null"],"format":"uint64","minimum":0.0},{"type":["integer","null"],"format":"uint64","minimum":0.0}],"maxItems":3,"minItems":3}},"definitions":{"ArchiveFormat":{"type":"string","enum":["tar.gz","zip"]},"ArchiveInfo":{"type":"object","required":["format","internal-path","post-remove"],"properties":{"format":{"$ref":"#/definitions/ArchiveFormat"},"internal-path":{"type":"string"},"post-remove":{"description":"Paths to remove after extraction (relative to the new directory)","type":"array","items":{"type":"string"}}}},"GenericResource":{"oneOf":[{"description":"A remote file to download via provided URL","type":"object","required":["remote"],"properties":{"remote":{"type":"object","required":["template-path","url"],"properties":{"archive":{"description":"If the remote file is an archive, define the internal object to extract and the archive format","anyOf":[{"$ref":"#/definitions/ArchiveInfo"},{"type":"null"}]},"override-name":{"description":"Optional name of the remote file","type":["string","null"]},"sha512":{"description":"Optional SHA-512 hash of the remote file for verification","type":["string","null"]},"template-path":{"description":"Path the file should be written to inside the build","type":"string"},"url":{"description":"URL of the remote file","type":"string"},"use-variables":{"description":"Whether to use variables in the file","anyOf":[{"$ref":"#/definitions/VarFormat"},{"type":"null"}]},"user-agent":{"description":"Custom user agent to use for the download","type":["string","null"]}}}},"additionalProperties":false},{"description":"A file encoded with Base64","type":"object","required":["base64"],"properties":{"base64":{"type":"object","required":["base64","template-path"],"properties":{"base64":{"type":"string"},"template-path":{"description":"Path the file should be written to inside the build","type":"string"},"use-variables":{"description":"Whether to use variables in the file","anyOf":[{"$ref":"#/definitions/VarFormat"},{"type":"null"}]}}}},"additionalProperties":false},{"description":"Copy file from Volkanic include folder to template","type":"object","required":["include"],"properties":{"include":{"type":"object","required":["id","template-path"],"properties":{"id":{"type":"string"},"template-path":{"description":"Path the file should be written to inside the build","type":"string"},"use-variables":{"description":"Whether to use variables in the file","anyOf":[{"$ref":"#/definitions/VarFormat"},{"type":"null"}]}}}},"additionalProperties":false}]},"ServerRuntimeResource":{"oneOf":[{"type":"object","required":["jdk"],"properties":{"jdk":{"type":"object","required":["jar-path","jdk-args","server-args","version"],"properties":{"jar-path":{"description":"Path to JAR executable","type":"string"},"jdk-args":{"description":"Adds additional JDK arguments","type":"array","items":{"type":"string"}},"server-args":{"description":"Adds additional arguments for JAR executable","type":"array","items":{"type":"string"}},"version":{"type":"string"}}}},"additionalProperties":false}]},"VarFormat":{"type":"string","enum":["dollar-curly"]}}}

=== 8Bitz0/volkanicmc-construct/vktemplates/overlays/add-geyser.json
{
  "$schema": "https://raw.githubusercontent.com/8Bitz0/volkanicmc-construct/refs/heads/main/schemas/format-3-overlay.json",
  "template-format": 3,
  "name": "Add GeyserMC to Spigot",
  "description": "Add GeyserMC to a Spigot server",
  "author": "VolkanicMC",
  "version": [
    1,
    0,
    0
  ],
  "resources": [
    {
      "remote": {
        "url": "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot",
        "override-name": "Geyser-Spigot.jar",
        "template-path": "plugins/Geyser-Spigot.jar"
      }
    },
    {
      "remote": {
        "url": "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot",
        "override-name": "floodgate-spigot.jar",
        "template-path": "plugins/floodgate-spigot.jar"
      }
    }
  ],
  "saveables": []
}
