=== 8Bitz0/volkanicmc-construct/schemas/format-2_draft1.json
{"$schema":"http://json-schema.org/draft-07/schema#","title":"Template","type":"object","required":["description","name","resources","runtime","saveables","template-format","variables"],"properties":{"author":{"description":"Simple identifier of the author.","type":["string","null"]},"description":{"description":"Longer description of the template.\n\nExample: \"Server running vanilla Minecraft 1.12.2\"","type":"string"},"name":{"description":"Name of the template. The name should briefly describe and identify the template.\n\nExample: \"1.12.2 Vanilla\"","type":"string"},"resources":{"description":"List of additional resources (e.g. plugins, mods, configs, etc.)","type":"array","items":{"$ref":"#/definitions/GenericResource"}},"runtime":{"description":"Server runtime software.","allOf":[{"$ref":"#/definitions/ServerRuntimeResource"}]},"saveables":{"description":"List of files which should be saved (e.g. worlds, whitelists, etc.)","type":"array","items":{"type":"string"}},"template-format":{"type":"integer","format":"uint","minimum":0.0},"variables":{"description":"Variables neccessary for the template.","type":"array","items":{"$ref":"#/definitions/Var"}},"version":{"description":"Version of the template.","type":["array","null"],"items":[{"type":"integer","format":"uint64","minimum":0.0},{"type":["integer","null"],"format":"uint64","minimum":0.0},{"type":["integer","null"],"format":"uint64","minimum":0.0}],"maxItems":3,"minItems":3}},"definitions":{"ArchiveFormat":{"type":"string","enum":["tar.gz","zip"]},"ArchiveInfo":{"type":"object","required":["format","internal-path","post-remove"],"properties":{"format":{"$ref":"#/definitions/ArchiveFormat"},"internal-path":{"type":"string"},"post-remove":{"description":"Paths to remove after extraction (relative to the new directory)","type":"array","items":{"type":"string"}}}},"GenericResource":{"oneOf":[{"description":"A remote file to download via provided URL","type":"object","required":["remote"],"properties":{"remote":{"type":"object","required":["template-path","url"],"properties":{"archive":{"description":"If the remote file is an archive, define the internal object to extract and the archive format","anyOf":[{"$ref":"#/definitions/ArchiveInfo"},{"type":"null"}]},"override-name":{"description":"Optional name of the remote file","type":["string","null"]},"sha512":{"description":"Optional SHA-512 hash of the remote file for verification","type":["string","null"]},"template-path":{"description":"Path the file should be written to inside the build","type":"string"},"url":{"description":"URL of the remote file","type":"string"},"use-variables":{"description":"Whether to use variables in the file","anyOf":[{"$ref":"#/definitions/VarFormat"},{"type":"null"}]},"user-agent":{"description":"Custom user agent to use for the download","type":["string","null"]}}}},"additionalProperties":false},{"description":"A file encoded with Base64","type":"object","required":["base64"],"properties":{"base64":{"type":"object","required":["base64","template-path"],"properties":{"base64":{"type":"string"},"template-path":{"description":"Path the file should be written to inside the build","type":"string"},"use-variables":{"description":"Whether to use variables in the file","anyOf":[{"$ref":"#/definitions/VarFormat"},{"type":"null"}]}}}},"additionalProperties":false},{"description":"Copy file from Volkanic include folder to template","type":"object","required":["include"],"properties":{"include":{"type":"object","required":["id","template-path"],"properties":{"id":{"type":"string"},"template-path":{"description":"Path the file should be written to inside the build","type":"string"},"use-variables":{"description":"Whether to use variables in the file","anyOf":[{"$ref":"#/definitions/VarFormat"},{"type":"null"}]}}}},"additionalProperties":false}]},"ServerRuntimeResource":{"oneOf":[{"type":"object","required":["jdk"],"properties":{"jdk":{"type":"object","required":["jar-path","jdk-args","server-args","version"],"properties":{"jar-path":{"description":"Path to JAR executable","type":"string"},"jdk-args":{"description":"Adds additional JDK arguments","type":"array","items":{"type":"string"}},"server-args":{"description":"Adds additional arguments for JAR executable","type":"array","items":{"type":"string"}},"version":{"type":"string"}}}},"additionalProperties":false}]},"Var":{"oneOf":[{"type":"object","required":["static"],"properties":{"static":{"type":"object","required":["name","value"],"properties":{"name":{"type":"string"},"value":{"type":"string"}}}},"additionalProperties":false},{"type":"object","required":["user"],"properties":{"user":{"type":"object","required":["name"],"properties":{"default":{"type":["string","null"]},"name":{"type":"string"}}}},"additionalProperties":false}]},"VarFormat":{"type":"string","enum":["dollar-curly"]}}}

=== 8Bitz0/volkanicmc-construct/vktemplates/1-21-4-paper.json
{
  "template-format": 3,
  "name": "1.21.4 Paper",
  "description": "Server running Minecraft 1.21.4 with PaperMC",
  "author": "VolkanicMC",
  "version": [
    1,
    0,
    0
  ],
  "variables": [
    {
      "user": {
        "name": "PORT",
        "default": "25565"
      }
    },
    {
      "user": {
        "name": "MC_RESOURCES",
        "default": ""
      }
    },
    {
      "user": {
        "name": "MC_RESOURCES_SHA1",
        "default": ""
      }
    }
  ],
  "runtime": {
    "jdk": {
      "version": "21",
      "jar-path": "server.jar",
      "jdk-args": [
        "-XX:+AlwaysPreTouch",
        "-XX:+DisableExplicitGC",
        "-XX:+ParallelRefProcEnabled",
        "-XX:+PerfDisableSharedMem",
        "-XX:+UnlockExperimentalVMOptions",
        "-XX:+UseG1GC",
        "-XX:G1HeapRegionSize=8M",
        "-XX:G1HeapWastePercent=5",
        "-XX:G1MaxNewSizePercent=40",
        "-XX:G1MixedGCCountTarget=4",
        "-XX:G1MixedGCLiveThresholdPercent=90",
        "-XX:G1NewSizePercent=30",
        "-XX:G1RSetUpdatingPauseTimePercent=5",
        "-XX:G1ReservePercent=20",
        "-XX:InitiatingHeapOccupancyPercent=15",
        "-XX:MaxGCPauseMillis=200",
        "-XX:MaxTenuringThreshold=1",
        "-XX:SurvivorRatio=32",
        "-Dusing.aikars.flags=https://mcflags.emc.gs",
        "-Daikars.new.flags=true"
      ],
      "server-args": ["-nogui"]
    }
  },
  "resources": [
    {
      "remote": {
        "url": "https://api.papermc.io/v2/projects/paper/versions/1.21.4/builds/225/downloads/paper-1.21.4-225.jar",
        "sha512": "1e82f665cc342ef05b5231eb2609b99d0b438ef929b5313a0f4d50e5373ae504b6bcda53054c7e91930d62b2e3f7ed1710b2616f3bf6a435a191a628cc6bddd5",
        "template-path": "server.jar"
      }
    },
    {
      "include": {
        "id": "1-21-paper.properties",
        "use-variables": "dollar-curly",
        "template-path": "server.properties"
      }
    },
    {
      "include": {
        "id": "eula.txt",
        "template-path": "eula.txt"
      }
    }
  ],
  "saveables": [
    "logs/",
    "world/",
    "world_nether/",
    "world_the_end/",
    ".console_history",
    "banned-ips.json",
    "banned-players.json",
    "ops.json",
    "permissions.yml",
    "usercache.json",
    "version_history.json",
    "whitelist.json"
  ]
}
